OBJECTS := cache.o calling.o calling_wrapper.o context.o env.o function.o kplugs.o memory.o queue.o stack.o vm.o

kplugs_debug-objs = $(OBJECTS)
MAKECMD  := make -C "/lib/modules/`uname -r`/build" SUBDIRS=$(PWD)
CPPFLAGS := -Wall -x assembler-with-cpp
MKDIR    := mkdir

all:
	@$(MAKECMD) obj-m="kplugs_debug.o" EXTRA_CFLAGS="-DDEBUG" modules
clean:
	@$(MAKECMD) clean

